solvifyhub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('solvifyhub_app.urls')),
]

solvifyhub_app/urls.py
from django.urls import path
from . import views


app_name = 'solvifyhub'

urlpatterns = [
    path('', views.index, name="index"),
    path('business_consulting/', views.business_consulting, name="business_consulting"),
    path('contact/', views.contact, name="contact"),
    path('service/', views.service, name="service"),
    path('service_details/', views.service_details, name="service_details"),
    path('about/', views.about, name="about"),
    path('partner/', views.partner, name="partner"),
    path('career/', views.career, name="career"),
    path('event/', views.event, name="event"),
    path('event_single/', views.event_single, name="event_single"),
    path('team/', views.team, name="team"),
    path('blog/', views.blog, name="blog"),
    path('blog_details/', views.blog_details, name="blog_details"),
    path('overview/', views.overview, name="overview"),
    path('pricing/', views.pricing, name="pricing"),
    path('feature/', views.feature, name="feature"),
    path('case_studie/', views.case_studie, name="case_studie"),
    path('case_studie_single/', views.case_studie_single, name="case_studie_single"),
    path('new_release/', views.new_release, name="new_release"),
    path('solution/', views.solution, name="solution"),
    path('portfolio/', views.portfolio, name="portfolio"),
    path('portfolio_details/', views.portfolio_details, name="portfolio_details"),
    path('faq/', views.faq, name="faq"),
    path('company/', views.company, name="company"),
    path('how_we_do/', views.how_we_do, name="how_we_do"),
    path('how_we_do_single/', views.how_we_do_single, name="how_we_do_single"),
    path('our_field_details/', views.our_field_details, name="our_field_details"),
]

solvifyhub_app/models.py
from django.db import models

# Create your models here.

solvifyhub_app/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages

def index(request):
    return render(request, 'index.html')


def business_consulting(request):
    return render(request, 'business_consulting.html')


def contact(request):
    if request.method == "POST":
        full_name = request.POST.get('full_name')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        state = request.POST.get('state')
        country = request.POST.get('country')
        message = request.POST.get('message')

        mail_subject = "Solvify Hub: GOT a LEAD !!!"
        print("WE are in Contact form")
        send_mail(
            subject=mail_subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.EMAIL_HOST_USER],
            fail_silently=True,
        )
        return redirect('solvifyhub:index')
    return render(request, 'contact.html')


def service(request):
    return render(request, 'service.html')


def service_details(request):
    return render(request, 'service_details.html')


def about(request):
    return render(request, 'about.html')


def partner(request):
    return render(request, 'partner.html')


def career(request):
    return render(request, 'career.html')


def event(request):
    return render(request, 'event.html')


def event_single(request):
    return render(request, 'event_single.html')


def team(request):
    return render(request, 'team.html')


def blog(request):
    return render(request, 'blog.html')


def blog_details(request):
    return render(request, 'blog_details.html')


def overview(request):
    return render(request, 'overview.html')


def pricing(request):
    return render(request, 'pricing.html')


def feature(request):
    return render(request, 'feature.html')


def case_studie(request):
    return render(request, 'case_studie.html')


def case_studie_single(request):
    return render(request, 'case_studie_single.html')


def new_release(request):
    return render(request, 'new_release.html')


def solution(request):
    return render(request, 'solution.html')


def career(request):
    return render(request, 'career.html')


def portfolio(request):
    return render(request, 'portfolio.html')


def portfolio_details(request):
    return render(request, 'portfolio_details.html')


def faq(request):
    return render(request, 'faq.html')


def company(request):
    return render(request, 'company.html')


def how_we_do(request):
    return render(request, 'how_we_do.html')


def how_we_do_single(request):
    return render(request, 'how_we_do_single.html')


def our_field_details(request):
    return render(request, 'our_field_details.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <!-- ========== Meta Tags ========== -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ========== Page Title ========== -->
    <title>{% block title %}  {% endblock %}</title>

    <!-- ========== Start Fonts Style ========== -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100;0,9..40,200;0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800;1,9..40,100;1,9..40,200;1,9..40,300;1,9..40,400;1,9..40,500;1,9..40,600&amp;family=Syne:wght@400;500;600&amp;family=Yantramanav:wght@100;300;400;500;700;900&amp;display=swap" rel="stylesheet">

    <!-- ========== Start Stylesheet ========== -->
    <link rel="stylesheet" href="{% static 'css/iconoir.css' %}">
    <link rel="stylesheet" href="{% static 'css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- ========== End Stylesheet ========== -->

    {% block extra_css %}
    {% endblock %}
</head>

<body>

    {% block content %}
    {% endblock %}

    <script>
        function submit_contact_form(){
            document.getElementById('contact_form').submit();

        }
    </script>
    <!-- jQuery Frameworks
    ============================================= -->
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/gsap.min.js' %}"></script>
    <script src="{% static 'js/Draggable.min.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/client-marquee.js' %}"></script>
    <script src="{% static 'js/theme-custom.js' %}"></script>
    <script src="{% static 'js/form1.js' %}"></script>
    <script src="{% static 'js/subscribe-form.js' %}"></script>


    {% block extra_js %}
    {% endblock %}
</body>


<!-- Mirrored from wpriverthemes.com/HTML/synck/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 07 Jan 2024 06:45:02 GMT -->
</html>

templates/components/why_our_services_better_section.html
{% load static %}

<section class="about-service3-area">
    <div class="custom-container">
        <div class="custom-row align-items-center">
            <div class="img-box">
                <img src="{% static 'img/about-service-2.png' %} " alt="About" />
            </div>

            <div class="content-box">
                <h1>Why our services are <br>
                    better than others?</h1>
                <p>We don't believe in a one-size-fit-all approach. Our services are carefully customized to suit your specific need, ensuring you to achieve your goals.</p>
                <p>We believe in delivering value that extends  your beyond the immediate project. Our services are designed to provide a long-term benefits.</p>
                <ul>
                    <li>
                        <i class="las la-check"></i> PPD Development
                    </li>
                    <li>
                        <i class="las la-check"></i> Quick Response
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

templates/faq.html
{% extends 'base.html' %}
{% load static %}
{% block title %} FAQ {% endblock %}
{% block content %}

    {% include 'includes/navbar.html' %}




        <!-- Faq Hero -->
        <section class="hero-service-wrap hero-section-wrap hero-portfolio-wrap hero-faq-wrap">
            <div class="hero-section-content-wrap">
                <div class="custom-container">
                    <div class="hero-portfolio-body">
                        <div class="hero-section-content text-center">
                            <h5 class="section-subtitle">FAQ</h5>
                            <h1 class="section-title fade-in">Our expert team give answers to <br>
                                your common questions</h1>
                            <p>Welcome to our FAQs section, where we address the most common questions and <br>
                                queries our clients and visitors often have.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <!-- Faq -->
        <section class="faq-area  faq-style-2-area">
            <div class="custom-container">
                <div class="faq-inner">

                    <h5 class="section-subtitle">FAQ SECTION</h5>
                    <h1 class="section-title">Frequently asked questions</h1>

                    <div class="faq-items-box">
                        <div class="faq-col">
                            <div  id="accordion">
                                <div class="faq-box">
                                    <h5 class="card-header" id="headingOne">
                                        <button data-bs-toggle="collapse" data-bs-target="#collapseOne"
                                            aria-expanded="true" aria-controls="collapseOne">
                                            <div class="icon">
                                                <img src="{% static 'img/question-icon.svg' %} " alt="Icon" />
                                            </div> What does your company will provide?
                                        </button>
                                    </h5>

                                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                                        data-parent="#accordion">
                                        <div class="card-body">
                                            At our IT service company, we give offer a comprehensive range of Web, App and Cloud solutions,
                                            including managed IT in services and network infrastructure setup.
                                        </div>
                                    </div>
                                </div>
                                <div class="faq-box">
                                    <h5 class="card-header" id="headingSix">
                                        <button data-bs-toggle="collapse" data-bs-target="#collapseSix"
                                            aria-expanded="false" aria-controls="collapseSix">
                                            <div class="icon">
                                                <img src="{% static 'img/question-icon.svg' %} " alt="Icon" />
                                            </div> How can we get started with your services?
                                        </button>
                                    </h5>

                                    <div id="collapseSix" class="collapse" aria-labelledby="headingSix"
                                        data-parent="#accordion2">
                                        <div class="card-body">
                                            To get started with our services, simply contact us through our website or give us a call. Our team will guide you through the process, ensuring a smooth start.
                                        </div>
                                    </div>
                                </div>
                                <div class="faq-box">
                                    <h5 class="card-header" id="headingTwo">
                                        <button data-bs-toggle="collapse" data-bs-target="#collapseTwo"
                                            aria-expanded="false" aria-controls="collapseTwo">
                                            <div class="icon">
                                                <img src="{% static 'img/question-icon.svg' %} " alt="Icon" />
                                            </div> Do you offer training for employees?
                                        </button>
                                    </h5>

                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                        data-parent="#accordion">
                                        <div class="card-body">
                                            Absolutely! We provide comprehensive training sessions to ensure your team is proficient with the tools and processes we implement, fostering a smooth transition and ongoing success.
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="faq-col">
                            <div id="accordion2">
                                <div class="faq-box">
                                    <h5 class="card-header" id="headingFour">
                                        <button data-bs-toggle="collapse" data-bs-target="#collapseFour"
                                            aria-expanded="true" aria-controls="collapseFour">
                                            <div class="icon">
                                                <img src="{% static 'img/question-icon.svg' %} " alt="Icon" />
                                            </div> Can you assist with recovery planning?
                                        </button>
                                    </h5>

                                    <div id="collapseFour" class="collapse show" aria-labelledby="headingFour"
                                        data-parent="#accordion2">
                                        <div class="card-body">
                                            Yes, our team offers expert recovery planning services to ensure your business is prepared for any contingency, minimizing downtime and protecting your data.
                                        </div>
                                    </div>
                                </div>
                                <div class="faq-box">
                                    <h5 class="card-header" id="headingFive">
                                        <button data-bs-toggle="collapse" data-bs-target="#collapseFive"
                                            aria-expanded="false" aria-controls="collapseFive">
                                            <div class="icon">
                                                <img src="{% static 'img/question-icon.svg' %} " alt="Icon" />
                                            </div> Can you help with cloud management?
                                        </button>
                                    </h5>

                                    <div id="collapseFive" class="collapse" aria-labelledby="headingFive"
                                        data-parent="#accordion2">
                                        <div class="card-body">

                                            Yes! We specialize in efficient, secure AWS cloud management solutions.
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <!-- <div class="faq-items-box">
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>What does your company will provide?</h3>
                                <p>At our IT service company, we give offer a comprehensive range of server solutions, including managed IT in services, network infrastructure setup.</p>
                            </div>
                        </div>
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>What does your company will provide?</h3>
                                <p>At our IT service company, we give offer a comprehensive range of server solutions, including managed IT in services, network infrastructure setup.</p>
                            </div>
                        </div>
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>Do you offer 24/7 support for services?</h3>
                            </div>
                        </div>
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>Can you assist with recovery planning?</h3>
                            </div>
                        </div>
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>Can you help with cloud management?</h3>
                            </div>
                        </div>
                        <div class="faq-box">
                            <div class="icon">
                                <img src="./{% static 'img/question-icon.svg' %} " alt="Icon"/>
                            </div>
                            <div class="content-body">
                                <h3>How can get started with your services?</h3>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </section>


        <!-- About -->
        <section class="about-service3-area">
            <div class="custom-container">
                <div class="custom-row align-items-center">
                    <div class="img-box">
                        <img src="{% static 'img/about-service-2.png' %} " alt="About" />
                    </div>

                    <div class="content-box">
                        <h1>Why our services are <br>
                            better than others?</h1>
                        <p>We don't believe in a one-size-fit-all approach. Our services are carefully customized to suit your specific need, ensuring you to achieve your goals.</p>
                        <p>We believe in delivering value that extends  your beyond the immediate project. Our services are designed to provide a long-term benefits.</p>
                        <ul>
                            <li>
                                <i class="las la-check"></i> Fast Delivery
                            </li>
                            <li>
                                <i class="las la-check"></i> Quick Response
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>


        <!-- CTA -->
        <section class="cta-area cta-area2">
            <div class="custom-container">
                <div class="cta-body text-center d-flex align-items-center justify-content-between">
                    <img src="{% static 'img/bg-shape-12.png' %} " alt="Shape" class="animation-slide-right bg-shape"/>
                    <div class="left">
                        <div class="our-expert-team-box">
                            <div class="our-expert-team-box-inner d-flex align-items-center">
                                <div class="imgs d-flex align-items-center">
                                    <img src="{% static 'img/small-img-4.png' %} " alt="team" />
                                    <img src="{% static 'img/small-img-3.png' %} " alt="team" />
                                    <img src="{% static 'img/small-img-2.png' %} " alt="team" />
                                    <img src="{% static 'img/small-img-1.png' %} " alt="team" />
                                </div>
                            </div>
                        </div>
                        <h2>Build your project with us, Make it world class</h2>
                        <p>Our projects are born from a passion for innovation that knows no bounds.</p>
                    </div>
                    <a href="{% url 'solvifyhub:contact' %}" class="theme-btn">Book an appointment now</a>

                </div>
            </div>
        </section>



        {% include 'includes/lets_get_in_touch_form.html' %}
        {% include 'includes/footer.html' %}
        {% endblock %}

templates/includes/footer.html
        {% load static %}
        <!-- Footer -->
        <footer class="footer-area">
            <img src="{% static 'img/bg-shape-4.svg' %} " alt="Shape" class="animation-slide-right bg-shape" />
            <div class="footer-top">
                <div class="custom-container">
                    <div class="custom-row align-items-end justify-content-between">
                        <div class="left-content">
                            <a style="color: white;" href="index-2.html" class="logo">
                                <!-- <img src="{% static '' %} img/logo-white.svg" alt="Logo" /> -->
                                Solvify Hub
                            </a>
                            <p>We provide the expertise and support to <br>
                                propel your business forward.</p>
                            <form action="https://wpriverthemes.com/HTML/synck/assets/mail/subscribe.php" method="POST" class="subscribe-form">
                                <div class="subscribe-box d-flex">
                                    <input type="email" id="email" name="email" placeholder="Enter Your Email" />
                                    <button id="submit2" class="theme-btn">Get Started</button>
                                </div>
                                <!-- Alert Message -->
                                <div class="input-row">
                                    <div class="input-group alert-notification">
                                        <div id="alert-message-subscribe" class="alert-msg"></div>
                                    </div>
                                </div>
                            </form>
                            <!-- <div class="footer-clients d-flex align-items-center">
                                <div class="footer-client-img">
                                    <img src="{% static 'img/youtube.svg' %} " alt="Youtube" />
                                </div>
                                <div class="footer-client-img">
                                    <img src="{% static 'img/webflow.svg' %} " alt="webflow" />
                                </div>
                                <div class="footer-client-img">
                                    <img src="{% static 'img/upwork.svg' %} " alt="upwork" />
                                </div>
                                <div class="footer-client-img">
                                    <img src="{% static 'img/shopify.svg' %} " alt="shopify" />
                                </div>
                            </div> -->
                        </div>

                        <div class="right-content">
                            <div class="right-content-inner">
                                <h2>Let’s get started on something great</h2>
                                <p>Our team of IT experts looks forward to meeting with you <br>
                                    and providing valuable insights tailored to your business.</p>
                                <a href="{% url 'solvifyhub:contact' %}" class="theme-btn">Get an appointment now</a>

                                <div class="footer-experience d-flex align-items-center">

                                    <div class="footer-experience-item">
                                        <h1>Quick</h1>
                                        <p>Response Time</p>
                                    </div>
                                    <div class="footer-experience-item">
                                        <h1>99%</h1>
                                        <p>Client Satisfaction</p>
                                    </div>
                                    <div class="footer-experience-item">
                                        <h1>4+ <span>Years</span></h1>
                                        <p>Field Experience</p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer-bottom">
                <div class="custom-container">
                    <div class="custom-row">
                        <div class="footer-all-links-wrap justify-content-between d-flex">
                            <div class="footer-links">
                                <h3>Services</h3>
                                <ul>
                                    <li><a href="service-details.html">IT Support</a></li>
                                    <li><a href="service-details.html">Web Design</a></li>
                                    <li><a href="service-details.html">Development</a></li>
                                    <li><a href="service-details.html">AWS Solutions <span class="new">New</span></a></li>
                                    <li><a href="service-details.html">E-Commerce Shopify</a></li>
                                    <li><a href="service-details.html">Digital Marketing</a></li>
                                </ul>
                            </div>
                            <div class="footer-links">
                                <h3>Company</h3>
                                <ul>
                                    <li><a href="blog.html">Blog</a></li>
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="partner.html">Partners</a></li>
                                    <li><a href="career.html">Careers</a></li>
                                    <li><a href="event.html">Events</a></li>
                                    <li><a href="team.html">Team</a></li>
                                </ul>
                            </div>
                            <div class="footer-links">
                                <h3>Product</h3>
                                <ul>
                                    <li><a href="case-studie.html">Case Studies </a></li>
                                    <li><a href="pricing.html">Our Pricing</a></li>
                                    <li><a href="feature.html">Features</a></li>
                                    <li><a href="overview.html">Overview</a></li>
                                    <li><a href="new-release.html">New Releases</a></li>
                                    <li><a href="solution.html">Solutions</a></li>
                                </ul>
                            </div>
                            <div class="footer-links">
                                <h3>Our Fields</h3>
                                <ul>
                                    <li><a href="our-field-details.html">Cloud Development</a></li>
                                    <li><a href="our-field-details.html">Web Development</a></li>
                                    <li><a href="our-field-details.html">App Development</a></li>
                                </ul>
                            </div>


                        </div>

                        <div class="footer-contact-info">
                            <div class="footer-contact-info-item">
                                <h4>Phone</h4>
                                <p>
                                    <a href="tel:+91-742-708-9473">+91-742-708-9473</a> <br>
                                    <a href="tel:+91-886-624-9910">+91-886-624-9910</a> <br>
                                    <a href="tel:+91-910-468-4900">+91-910-468-4900</a>
                                </p>
                            </div>
                            <div class="footer-contact-info-item">
                                <h4>Mail</h4>
                                <p>
                                    <a href="mailto:vaibhavpaliwal678@mail.com">vaibhavpaliwal678@gmail.com</a> <br>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="copyright-area">
                <div class="custom-container">
                    <div class="custom-row d-flex align-items-center justify-content-between">
                        <ul class="social-links d-flex align-items-center">
                            <li><a href="#">
                                <i class="iconoir-dribbble"></i>
                            </a></li>
                            <li><a href="#">
                                <i class="iconoir-twitter"></i>
                            </a></li>
                            <li><a href="#">
                                <i class="iconoir-instagram"></i>
                            </a></li>
                            <li><a href="#">
                                <i class="iconoir-linkedin"></i>
                            </a></li>
                        </ul>

                        <p>&copy; 2024 All rights reserved by Solvify Hub</p>
                    </div>
                </div>
            </div>
        </footer>